### ISSUE TITLE
Arch package

### ISSUE THREAD

**Issue by fuero** [HenrikBengtsson/x86-64-level#8]
just fyi - I created a package for Archlinux for x86-64-level, find it here:

https://aur.archlinux.org/packages/x86-64-level

**Comment by HenrikBengtsson** [comment]
Excellent. Thank you. Let me know if there's anything I can do on my end to simplify or make this better. (I have zero experience how such packaging takes place).

**Comment by HenrikBengtsson** [comment]
I've added:

[![Packaging status](https://repology.org/badge/vertical-allrepos/x86-64-level.svg)](https://repology.org/project/x86-64-level/versions)

to the README.
